name: Driver2Comm
channels:
  - conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - defaults
dependencies:
  - python>=3.10
  - pip>=20.2.2
  - pip:
    - pandas>=2.1.4
    - numpy>=1.26.2
    - statsmodels>=0.14.1
    - networkx>=3.2.1
    - matplotlib>=3.8.2
    
